version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wild-rydes-async-msg-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xouyhykecfms"
s3_prefix = "wild-rydes-async-msg-1"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
