AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Wild Rydes Asynchronous Messaging Workshop - Lab 1

Globals:
  Function:
    Timeout: 10
    Runtime: python3.7
    Tags:
      project: wild-rydes
      workshop: asynchronous-messaging-workshop
      author: aws
      owner: sajid.ali@trilogy.com   # Add the owner tag to the Globals section

Resources:
  SubmitRideCompletionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: unicorn-management-service/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref RidesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RidesTable
      Events:
        WildRydes:
          Type: Api
          Properties:
            Path: /submit-ride-completion
            Method: post
    Tags:   # Add the owner tag to the SubmitRideCompletionFunction resource
      - Key: owner
        Value: sajid.ali@trilogy.com

################################################
## MICROSERVICES BACKENDS BASED ON AWS LAMBDA ##
################################################
  CustomerAccountingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: customer_accounting_service/
      Handler: app.lambda_handler
    Tags:   # Add the owner tag to the CustomerAccountingFunction resource
      - Key: owner
        Value: sajid.ali@trilogy.com

  CustomerNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: customer_notification_service/
      Handler: app.lambda_handler
    Tags:   # Add the owner tag to the CustomerNotificationFunction resource
      - Key: owner
        Value: sajid.ali@trilogy.com

  ExtraordinaryRidesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: extraordinary_rides_service/
      Handler: app.lambda_handler
    Tags:   # Add the owner tag to the ExtraordinaryRidesFunction resource
      - Key: owner
        Value: sajid.ali@trilogy.com

  RidesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "Rides-${AWS::StackName}"
      PrimaryKey:
        Name: id
        Type: String
    Tags:   # Add the owner tag to the RidesTable resource
      - Key: owner
        Value: sajid.ali@trilogy.com

Outputs:
  UnicornManagementServiceApiSubmitRideCompletionEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for SubmitRideCompletion function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/submit-ride-completion/"

  SubmitRideCompletionFunction:
    Description: "SubmitRideCompletionFunction Lambda Function ARN"
    Value: !GetAtt SubmitRideCompletionFunction.Arn

  CustomerAccountingFunction:
    Description: "CustomerAccountingFunction Lambda Function ARN"
    Value: !GetAtt CustomerAccountingFunction.Arn

  CustomerNotificationFunction:
    Description: "CustomerNotificationFunction Lambda Function ARN"
    Value: !GetAtt CustomerNotificationFunction.Arn

  ExtraordinaryRidesFunction:
    Description: "ExtraordinaryRidesFunction Lambda Function ARN"
    Value: !GetAtt ExtraordinaryRidesFunction.Arn

  SubmitRideCompletionFunctionIamRole:
    Description: "Implicit IAM Role created for SubmitRideCompletion function"
    Value: !GetAtt SubmitRideCompletionFunctionRole.Arn

  RidesTable:
    Description: "Amazon DynamoDB table ARN for Rides table"
    Value: !Ref RidesTable
